version: '3'

services:
  database:
    image: postgres
    container_name: car_rental_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=car_rental
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: car_rental_app
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local